services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    expose:
      # <Host Port>:<Container Port>
      - 3001
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.medisync-uptime.rule=Host(`medisync-uptime.toctive.com`)
      - "traefik.http.routers.medisync-uptime.entrypoints=websecure"
      - "traefik.http.routers.medisync-uptime.tls.certResolver=letsencrypt"
      - traefik.http.services.medisync-uptime.loadbalancer.server.port=3001

networks:
  dokploy-network:
    external: true
